### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by jigarmistry** [tryexceptpass/sofi#29]
Hello All,

Can we change the folder structure of sofi? Can we put all elements py files into element folder ?
With this we can easily understand the elements and looks good for development. Your thoughts on it.

Congo for great work. Looking forward to work on this.

**Comment by tryexceptpass** [comment]
Yes that's an issue I have with the current setup. Asides from the neat freak in me wanting to fix it up, I also think it's a good idea for separating app vs graphics, such that if we ever want to split off the Bootstrap portion, it's easy.

It also makes more sense to do something like `from sofi.ui import Widget` and `from sofi.app import Sofi`

**Comment by jigarmistry** [comment]
`It also makes more sense to do something like from sofi.ui import Widget and from sofi.app import Sofi`

This is something that I wanted to see.
