### ISSUE TITLE
Milestone / Future Work

### ISSUE THREAD

**Issue by jigarmistry** [tryexceptpass/sofi#30]
Hello,

Can we have list of pending/future work(wiki like) ? So one can see and try to contribute for this great module.

**Comment by jigarmistry** [comment]
@tryexceptpass Please provide the list of items for contribution

**Comment by tryexceptpass** [comment]
I'm working on something more detailed. However, the plan is to track it through issues marked as `tasks` or `features`.

**Comment by LordZane** [comment]
What do you guys think of having an option to generate an electron app? I would love this feature

**Comment by tryexceptpass** [comment]
@jigarmistry I've added a bunch of issues tagged as `tasks` to track the immediate list of items that need to be added to finish supporting Bootstrap stuff.

@LordZane I haven't made anything with electron yet, but I've been aware of it for a little while. Some googling around and quick look at docs makes me think that it would be possible to generate the HTML and JS needed to use the electron packaging system, but you would still need a python backend. However, this may not be a big deal given websockets don't require your app to be on the client. Let's continue the discussion at #67.
