### ISSUE TITLE
Add Bootstrap Page Header

### ISSUE THREAD

**Issue by tryexceptpass** [tryexceptpass/sofi#45]
Provide a `PageHeader` object that represents the `div` with `page-header` class.
* Provide a shortcut for adding subtext through a property or method that wraps it in `small`

**Comment by jigarmistry** [comment]
Should we give option to set size of header(h1,h2...) ? 

`<div class = "page-header">
   
   <h1>
      Example page header 
      <small>Subtext for header</small>
   </h1>
   
</div>`

**Comment by tryexceptpass** [comment]
No, it seems `h1` is what wraps defines it.

**Comment by jigarmistry** [comment]
So we need to harcode the H1 into page header object. Is it ?

**Comment by tryexceptpass** [comment]
Yes, for now. If we need to, we can change it later.
